runtime: nodejs8

instance_class: F1

handlers:

- url: /
  static_dir: build

- url: /manifest.json
  static_files: build/manifest.json
  upload: build/manifest.json

- url: /
  static_files: build/index.html
  upload: build/index.html